Repository TUK2024CD-Studymate/frontend, pull requests merged in 2024-04, with the labels that each got.

#85 [Design] 온보딩 페이지 구현
  src/App.tsx
  src/assets/images/onboard_img_1.png
  src/assets/images/onboard_img_2.png
  src/assets/images/onboard_img_3.png
  src/assets/images/onboard_text_1.png
  src/assets/images/onboard_text_2.png
  src/assets/images/onboard_text_3.png
  src/assets/images/onboard_text_4.png
  src/assets/images/onboard_text_5.png
  src/assets/images/onboard_text_6.png
  src/assets/images/onboarding1.png
  src/components/Header.tsx
  src/components/Header2.tsx
  src/components/main/MainFirst.tsx
  src/components/main/MainFourth.tsx
  src/components/main/MainSecond.tsx
  src/components/main/MainThird.tsx
  src/components/main/StartNav.tsx
  src/pages/MainPage.tsx
Labels: 기능구현, 디자인

#87 [Fix] 온보딩 페이지 수정
  src/components/main/MainFirst.tsx
  src/components/main/MainFourth.tsx
  src/components/main/MainHeader1.tsx
  src/components/main/MainHeader2.tsx
  src/components/main/MainSecond.tsx
  src/components/main/MainThird.tsx
  src/components/main/StartNav.tsx
  src/components/main/useOnScreen.ts
  src/pages/MainPage.tsx
Labels: 기능구현, 오류수정, 디자인

#78 [Fix] 게시글 필터링 수정
  package-lock.json
  package.json
  src/components/Login.tsx
  src/pages/PostsPage/DetailMainPostsPage.tsx
  src/pages/PostsPage/MainPostsPage.tsx
  src/pages/PostsPage/QuestionPostsPage.tsx
  src/pages/PostsPage/StudyPostsPage.tsx
  src/pages/StudyPage.tsx
  yarn.lock
Labels: 기능구현, 오류수정

#83 [Feat] 게시글 좋아요/댓글수 구현
  src/pages/PostsPage/DetailMainPostsPage.tsx
  src/pages/PostsPage/DetailQuestionPostsPage.tsx
  src/pages/PostsPage/DetailStudyPostPage.tsx
  src/pages/PostsPage/MainPostsPage.tsx
  src/pages/PostsPage/QuestionPostsPage.tsx
  src/pages/PostsPage/StudyPostsPage.tsx
  src/store/store.ts
Labels: 기능구현

#89 [Refactor] 필요없는 코드 삭제 및 수정
  src/pages/PostsPage/DetailMainPostsPage.tsx
  src/pages/PostsPage/DetailStudyPostPage.tsx
  src/pages/PostsPage/StudyPostsPage.tsx
  src/store/store.ts
Labels: 리팩토링

#92 [fix] 로그인 api response body 변경에 따른 코드 수정
  src/components/Login.tsx
Labels: 오류수정

#93 [Fix]스터디 기록 수정
  package.json
  src/components/AddStudyModal.tsx
  src/components/StudyCalendar.tsx
  src/pages/StudyPage.tsx
  yarn.lock
Labels: 리팩토링

#97 [Refactor] moment메소드에서 dayjs로 변경
  src/pages/StudyPage.tsx
Labels: 리팩토링

#101 [Feat] 매칭된 유저 리스트 UI 변경 및 리뷰 모달창 구현
  index.html
  package.json
  src/App.tsx
  src/assets/images/김영한.png
  src/components/Navbar2.tsx
  src/components/ReviewModal.tsx
  src/components/SelectUser.tsx
  src/pages/OnlinePage/SelectUserPage.tsx
  src/store/store.ts
  yarn.lock
Labels: 기능구현, 디자인

#103 [Design] 온보딩 페이지 하단에 개인정보 보호정책 추가
  src/components/main/MainFooter.tsx
  src/components/main/MainFourth.tsx
  src/components/main/MainSecond.tsx
  src/components/main/MainThird.tsx
  src/pages/MainPage.tsx
  src/store/store.ts
Labels: 디자인

#98 [Fix]게시판 추가기능 구현 및 css 수정
  src/App.tsx
  src/components/AddStudyModal.tsx
  src/components/sidebar/Postsbar.tsx
  src/pages/PostsPage/DetailMainPostsPage.tsx
  src/pages/PostsPage/DetailQuestionPostsPage.tsx
  src/pages/PostsPage/DetailStudyPostPage.tsx
  src/pages/PostsPage/MainPostsPage.tsx
  src/pages/PostsPage/QuestionPostsPage.tsx
  src/pages/PostsPage/StudyPostsPage.tsx
  src/pages/PostsPage/WritingPostsPage.tsx
  src/pages/StudyPage.tsx
  src/store/store.ts
Labels: 기능구현, 오류수정

#104 [Fix] 스터디기록 생성 무한루프 에러 해결
  src/components/AddStudyModal.tsx
  src/components/StudyPostingModal.tsx
  src/pages/StudyPage.tsx
Labels: 오류수정

#116 [design] 게시글 작성 페이지 퍼블리싱 수정
  src/pages/PostsPage/WritingPostsPage.tsx
  src/store/store.ts
Labels: 디자인

#113 [Fix] 비로그인시 로그인 페이지 리다이렉션, 매칭 시작 문구 수정
  src/App.tsx
  src/components/main/MainFourth.tsx
  src/components/main/MainSecond.tsx
  src/components/main/MainThird.tsx
  src/components/utils/ProtecetedRoute.tsx
  src/components/utils/useAuth.ts
  src/components/utils/useOnScreen.ts
  src/pages/OnlinePage/StartPage.tsx
Labels: 기능구현, 오류수정

#114 [design] 스터디 게시글 전체조회 css 수정
  src/pages/PostsPage/DetailMainPostsPage.tsx
  src/pages/PostsPage/DetailQuestionPostsPage.tsx
  src/pages/PostsPage/DetailStudyPostPage.tsx
  src/pages/PostsPage/MainPostsPage.tsx
  src/pages/PostsPage/QuestionPostsPage.tsx
  src/pages/PostsPage/StudyPostsPage.tsx
  src/store/store.ts
Labels: 디자인
