Repository TUK2024CD-Studymate/frontend, pull requests merged in 2024-03, with the labels that each got.

#40 [Feat] zustand 로 api url 상태관리적용
  src/components/Login.tsx
  src/components/SignUp.tsx
  src/pages/Mypage/ProfilePage.tsx
  src/store/store.ts
Labels: 기능구현

#45 [design] 회원가입 전화번호란 추가
  src/App.tsx
  src/components/SignUp.tsx
Labels: 디자인

#49 [fix] 회원가입 수정
  src/components/Header2.tsx
  src/components/SignUp.tsx
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
Labels: 기능구현, 리팩토링, 디자인

#59 [Feat] 채팅 페이지 기능 고도화 + 회원가입시 전화번호 인증
  src/components/Chat.tsx
  src/components/SignUp.tsx
Labels: 기능구현, 디자인

#63 [Refactor] 회원가입 코드 리팩토링
  src/components/SignUp.tsx
Labels: 기능구현, 리팩토링

#66 [Design] Navbar 변경
  src/App.tsx
  src/components/Navbar2.tsx
Labels: 기능구현, 디자인

#68 [Feat] 채팅 기능 구현
  package.json
  src/components/Chat.tsx
  yarn.lock
Labels: 기능구현, 디자인

#71 [Feat] 선택한 유저에게 LMS 알림 전송
  src/components/SelectUserModal.tsx
Labels: 기능구현, 디자인

#73 [refactor] 사용하지 않는 코드 삭제, 주석처리
  src/App.tsx
  src/components/AddStudyModal.tsx
  src/components/Chat.tsx
  src/components/ConfirmMatchingModal.tsx
  src/components/FindLoadingModal.tsx
  src/components/Header.tsx
  src/components/MatchingLoadingModal.tsx
  src/components/Navbar.tsx
  src/components/Navbar2.tsx
  src/components/SelectUserModal.tsx
  src/components/SignUp.tsx
  src/components/StudyCalendar.tsx
  src/components/StudyPostingModal.tsx
  src/main.tsx
  src/pages/LoginPage.tsx
  src/pages/OfflinePage.tsx
  src/pages/OnlinePage/SelectUserPage.tsx
  src/pages/OnlinePage/StartPage.tsx
  src/pages/PostsPage/WritingPostsPage.tsx
  src/pages/StudyPage.tsx
  src/pages/TestPage.tsx
Labels: 리팩토링

#75 [fix] 회원가입시 PR, blogurl 누락되는 문제해결
  src/components/SignUp.tsx
Labels: 오류수정
