Repository TUK2024CD-Studymate/frontend, pull requests merged in 2024-02, with the labels that each got.

#11 [Fix/#8] 회원가입 에러 해결
  src/components/SignUp.tsx
Labels: 오류수정

#10 [Design/#9] 게시판 페이지 퍼블리싱
  src/App.tsx
  src/assets/images/bubble.png
  src/assets/images/likeicon.png
  src/assets/images/unlikeicon.png
  src/components/Header.tsx
  src/components/MainPost.tsx
  src/components/Navbar.tsx
  src/components/QuestionsPost.tsx
  src/components/SideNavbar.tsx
  src/components/StudyPost.tsx
  src/pages/MainPostPage.tsx
  src/pages/QuestionPostPage.tsx
  src/pages/StudyPostPage.tsx
Labels: 디자인

#14 [Design] 공용컴포넌트, 마이페이지 퍼블리싱
  src/App.tsx
  src/assets/images/StudyMate.svg
  src/assets/images/comment.png
  src/assets/images/profile.png
  src/components/Header2.tsx
  src/components/Navbar2.tsx
  src/components/sidebar/MypageBar.tsx
  src/pages/Mypage/MatingListPage.tsx
  src/pages/Mypage/MyPostPage.tsx
  src/pages/Mypage/NotificationPage.tsx
  src/pages/Mypage/ProfilePage.tsx
  src/pages/OfflinePage.tsx
  src/pages/OnlinePage.tsx
Labels: 디자인

#15 [Design] 공용컴포넌트 + 마이페이지 퍼블리싱
  src/assets/images/comment2.png
  src/assets/images/divider1.png
  src/assets/images/people.png
  src/pages/Mypage/MatingListPage.tsx
  src/pages/Mypage/MyPostPage.tsx
Labels: 디자인

#19 [Fix] 로그인/회원가입 페이지 css 조정 및 리팩토링
  src/App.tsx
  src/components/Login.tsx
  src/components/SignUp.tsx
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
Labels: 기능구현, 리팩토링, 디자인

#23 [Design] 온라인 매칭 페이지 퍼블리싱
  src/components/Navbar2.tsx
  src/components/SelectUserModal.tsx
  src/pages/OnlinePage.tsx
Labels: 디자인

#29 [Design] 스터디 기록 페이지 퍼블리싱
  src/App.tsx
  src/assets/images/calender.png
  src/assets/images/play.png
  src/assets/images/stop.png
  src/pages/StudyPage.tsx
Labels: 디자인

#30 [Fix] 게시판 수정 및 추가 기능 구현
  src/App.tsx
  src/components/sidebar/Postsbar.tsx
  src/pages/Mypage/MyPostPage.tsx
  src/pages/PostsPage/DetailMainPostsPage.tsx
  src/pages/PostsPage/DetailQuestionPostsPage.tsx
  src/pages/PostsPage/DetailStudyPostPage.tsx
  src/pages/PostsPage/MainPostsPage.tsx
  src/pages/PostsPage/QuestionPostsPage.tsx
  src/pages/PostsPage/StudyPostsPage.tsx
  src/pages/PostsPage/WritingPostsPage.tsx
Labels: 기능구현, 리팩토링

#31 [Design] 채팅 페이지 퍼블리싱
  src/App.tsx
  src/assets/images/attach.png
  src/assets/images/photo.png
  src/components/Chat.tsx
  src/pages/ChatPage.tsx
Labels: 기능구현, 디자인

#33 [Design] 매칭 페이지 퍼블리싱
  package.json
  src/assets/images/accordionBtn.png
  src/assets/images/loading.png
  src/components/ConfirmMatchingModal.tsx
  src/components/FindLoadingModal.tsx
  src/components/Header2.tsx
  src/components/MatchingLoadingModal.tsx
  src/components/Navbar2.tsx
  src/components/SelectUserModal.tsx
  src/main.tsx
  src/pages/OnlinePage.tsx
  yarn.lock
Labels: 기능구현, 디자인
