Repository TUK2024CD-Studymate/frontend, pull requests merged in 2024-05, with the labels that each got.

#121 [Design] 채팅방 리스트 페이지 퍼블리싱
  src/App.tsx
  src/components/ChatList.tsx
  src/components/Navbar2.tsx
  src/components/utils/ProtecetedRoute.tsx
  src/components/utils/useAuth.ts
  src/pages/ChatPage.tsx
Labels: 디자인

#124 [feat] Server Sent Event 알림 기능 구현
  package.json
  src/App.tsx
  yarn.lock
Labels: 기능구현

#126 [feat] 온라인 매칭 질문 폼 수정 및 알고리즘 추가
  src/components/SelectUser.tsx
  src/pages/OnlinePage/StartPage.tsx
  src/store/store.ts
Labels: 기능구현, 리팩토링, 디자인

#130 [design] 스터디기록 수정된 피그마로 퍼블리싱
  package.json
  src/App.tsx
  src/components/AddStudyModal.tsx
  src/components/PieChart.tsx
  src/components/StudyCalendar.tsx
  src/components/sidebar/StatisticsBar.tsx
  src/pages/AddStudyPage.tsx
  src/pages/StudyPage.tsx
  src/store/store.ts
  yarn.lock
Labels: 디자인

#132 [Fix] 에러문구 추가 & id별 하트 이미지 변환
  src/pages/PostsPage/MainPostsPage.tsx
  src/pages/PostsPage/QuestionPostsPage.tsx
  src/pages/PostsPage/StudyPostsPage.tsx
Labels: 오류수정

#133 [Design]스켈레톤ui 구현
  src/components/skeleton/DetailSkeletonUI.tsx
  src/components/skeleton/SkeletonUI.tsx
  src/components/skeleton/StudySkeletonUI.tsx
  src/pages/PostsPage/DetailMainPostsPage.tsx
  src/pages/PostsPage/DetailQuestionPostsPage.tsx
  src/pages/PostsPage/DetailStudyPostPage.tsx
  src/pages/PostsPage/MainPostsPage.tsx
  src/pages/PostsPage/QuestionPostsPage.tsx
  src/pages/PostsPage/StudyPostsPage.tsx
Labels: 디자인

#134 [Feat] 채팅방 리스트 조회를 통한 채팅방 입장 기능 구현
  src/App.tsx
  src/assets/images/chatIcon.png
  src/components/Chat.tsx
  src/components/ChatList.tsx
  src/components/SelectUser.tsx
  src/pages/ChatPage.tsx
  src/pages/ChatRoomPage.tsx
  src/store/store.ts
Labels: 기능구현, 리팩토링, 디자인

#136 [Feat] 리뷰 작성 기능 구현
  src/App.tsx
  src/components/Chat.tsx
  src/components/ChatList.tsx
  src/components/SelectUser.tsx
  src/pages/ChatRoomPage.tsx
  src/pages/OnlinePage/CreateReviewModal.tsx
  src/store/store.ts
Labels: 기능구현, 리팩토링, 디자인

#138 [Feat] LMS -> 카카오 알림으로 변경
  src/components/SelectUser.tsx
Labels: 기능구현

#141 [Fix] DB 수정에 따른 데이터 key value 수정
  src/pages/OnlinePage/StartPage.tsx
  src/pages/PostsPage/MainPostsPage.tsx
  src/pages/PostsPage/WritingPostsPage.tsx
Labels: 오류수정

#143 [Fix] 백엔드 로직 수정에 따른 기능 수정
  src/components/Chat.tsx
  src/components/ChatList.tsx
  src/components/Header2.tsx
  src/components/SignUp.tsx
  src/pages/OnlinePage/CreateReviewModal.tsx
  src/pages/PostsPage/MainPostsPage.tsx
  src/store/store.ts
Labels: 기능구현, 리팩토링, 오류수정, 디자인

#146 [Refactor] 디렉토리 구조 변경 및 파일명 수정
  src/App.tsx
  src/components/Header.tsx
  src/components/Header2.tsx
  src/components/Navbar.tsx
  src/components/Navbar2.tsx
  src/components/chat/Chat.tsx
  src/components/chat/ChatList.tsx
  src/components/chat/CreateReviewModal.tsx
  src/components/matching/ConfirmMatchingModal.tsx
  src/components/matching/MatchingLoadingModal.tsx
  src/components/matching/ReviewModal.tsx
  src/components/matching/SelectUser.tsx
  src/components/matching/SelectUserModal.tsx
  src/pages/StudyPage.tsx
  src/pages/chat/ChatPage.tsx
  src/pages/chat/ChatRoomPage.tsx
  src/pages/matching/SelectUserPage.tsx
  src/pages/matching/StartPage.tsx
  src/pages/mypage/MatingListPage.tsx
  src/pages/mypage/MyPostPage.tsx
  src/pages/mypage/NotificationPage.tsx
  src/pages/mypage/ProfilePage.tsx
  src/pages/post/DetailMainPostsPage.tsx
  src/pages/post/DetailQuestionPostsPage.tsx
  src/pages/post/DetailStudyPostPage.tsx
  src/pages/post/MainPostsPage.tsx
  src/pages/post/QuestionPostsPage.tsx
  src/pages/post/StudyPostsPage.tsx
  src/pages/post/UpdatePostsPage.tsx
  src/pages/post/WritingPostsPage.tsx
Labels: 리팩토링

#150 [Feat] 스터디기록 수정 api로 연동
  src/components/AddSubjectModal.tsx
  src/components/ModifySubjectModal.tsx
  src/components/PieChart.tsx
  src/components/StudyCalendar.tsx
  src/components/sidebar/StatisticsBar.tsx
  src/components/skeleton/StudySkeletonUI.tsx
  src/pages/StudyPage.tsx
  src/store/store.ts
Labels: 기능구현

#149 [Design] 마이페이지 디자인 변경 & 스켈레톤 ui 적용
  src/components/Header.tsx
  src/components/sidebar/Profilebar.tsx
  src/components/skeleton/MyPageSkeletonUI.tsx
  src/pages/mypage/MatingListPage.tsx
  src/pages/mypage/MyPostPage.tsx
  src/pages/mypage/NotificationPage.tsx
  src/pages/mypage/ProfilePage.tsx
  src/pages/post/DetailMainPostsPage.tsx
  src/pages/post/DetailQuestionPostsPage.tsx
  src/pages/post/DetailStudyPostPage.tsx
  src/pages/post/MainPostsPage.tsx
  src/pages/post/QuestionPostsPage.tsx
  src/pages/post/StudyPostsPage.tsx
  src/store/store.ts
Labels: 디자인
