Repository TUK2024CD-Studymate/frontend, pull requests merged in 2024-06, with the labels that each got.

#155 [Fix] 리뷰 등록이 안되는 문제 해결
  src/components/chat/CreateReviewModal.tsx
  src/components/matching/SelectUser.tsx
  src/pages/matching/SelectUserPage.tsx
Labels: 오류수정, 디자인

#157 [Feat] 프로필 이미지 등록 구현
  src/App.tsx
  src/assets/images/profileimg.png
  src/components/Header.tsx
  src/components/StudyCalendar.tsx
  src/components/sidebar/Profilebar.tsx
  src/pages/mypage/ProfilePage.tsx
  src/pages/mypage/UpdateProfilePage.tsx
  src/pages/post/DetailMainPostsPage.tsx
  src/pages/post/DetailQuestionPostsPage.tsx
  src/pages/post/DetailStudyPostPage.tsx
  src/store/store.ts
Labels: 기능구현

#152 [Feat] 마이페이지 내 게시글 조회 & 내 질문 조회
  src/App.tsx
  src/components/Header.tsx
  src/components/sidebar/Profilebar.tsx
  src/pages/mypage/MatingListPage.tsx
  src/pages/mypage/MyPostPage.tsx
  src/pages/mypage/ProfilePage.tsx
  src/pages/mypage/UpdateProfilePage.tsx
  src/pages/post/DetailMainPostsPage.tsx
  src/pages/post/DetailQuestionPostsPage.tsx
  src/pages/post/DetailStudyPostPage.tsx
  src/pages/post/MainPostsPage.tsx
  src/pages/post/QuestionPostsPage.tsx
  src/pages/post/StudyPostsPage.tsx
  src/store/store.ts
Labels: 기능구현

#160 [feat] 매칭 퍼센트 적용
  src/assets/images/Loading.gif
  src/components/matching/SelectUser.tsx
  src/components/sidebar/Profilebar.tsx
  src/pages/matching/SelectUserPage.tsx
  src/store/store.ts
Labels: 기능구현, 오류수정, 디자인

#162 [feat] 채팅방 내역조회 및 게시글을 통한 생성
  src/components/chat/Chat.tsx
  src/pages/post/DetailMainPostsPage.tsx
  src/pages/post/DetailQuestionPostsPage.tsx
  src/pages/post/DetailStudyPostPage.tsx
Labels: 기능구현, 오류수정, 디자인

#163 [Feat] Header 프로필 이미지와 닉네임 캐싱처리
  src/components/Header.tsx
  src/pages/mypage/ProfilePage.tsx
  src/pages/mypage/UpdateProfilePage.tsx
Labels: 기능구현
